Repository chu-aie/os-2024, pull requests merged in 2024-05, with the labels that each got.

#172 fix: update book week12 by ypilseong
  src/os2024/book/week12/figs/OSTEP_31_Semaphores.jpeg
  src/os2024/book/week12/threads-cv.md
  src/os2024/book/week12/threads-sema.md
Labels: enhancement, Review effort [1-5]: 4

#176 Homework patch 3
  ad sa
  src/os2024/book/projects/202221014/hw-wk07.md
  src/os2024/book/projects/202221014/kv_store/Makefile
  src/os2024/book/projects/202221014/kv_store/database.txt
  src/os2024/book/projects/202221014/kv_store/kv_store
  src/os2024/book/projects/202221014/kv_store/src/kv_store.c
  src/os2024/book/projects/202221014/kv_store/src/kv_store.h
  src/os2024/book/projects/202221014/kv_store/src/main.c
  src/os2024/book/projects/202221014/project_manual.md
  src/ostep-homework/vm-freespace/malloc.py
Labels: documentation, enhancement, Review effort [1-5]: 3

#178 Entelecheia/issue169
  src/os2024/book/week11/threads-locks-usage.md
  src/os2024/book/week11/threads-locks.md
  src/os2024/book/week12/threads-cv.md
  src/os2024/book/week12/threads-sema.md
Labels: documentation, enhancement, Review effort [1-5]: 2
