Repository chu-aie/os-2024, pull requests merged in 2024-06, with the labels that each got.

#179 Entelecheia/issue173
  src/os2024/book/_toc.yml
  src/os2024/book/week09/dialogue.md
  src/os2024/book/week09/index.md
  src/os2024/book/week13/dialogue.md
  src/os2024/book/week13/file-devices.md
  src/os2024/book/week13/file-directory.md
  src/os2024/book/week13/fs-implementation.md
  src/os2024/book/week13/index.md
Labels: documentation, enhancement, Review effort [1-5]: 2

#181 fix: update book week13 by ypilseong
  src/os2024/book/week13/figs/devicesimg1.jpeg
  src/os2024/book/week13/figs/devicesimg2.jpeg
  src/os2024/book/week13/figs/devicesimg3.jpeg
  src/os2024/book/week13/figs/devicesimg4.jpeg
  src/os2024/book/week13/figs/devicesimg5.jpeg
  src/os2024/book/week13/figs/devicesimg6.jpeg
  src/os2024/book/week13/figs/devicesimg7.jpeg
  src/os2024/book/week13/figs/devicesimg8.jpeg
  src/os2024/book/week13/figs/devicesimg9.jpeg
  src/os2024/book/week13/figs/fileimg1.png
  src/os2024/book/week13/file-devices.md
  src/os2024/book/week13/file-directory.md
Labels: documentation, Review effort [1-5]: 3

#184 add 15w
  src/os2024/book/week15/dist-intro.md
  src/os2024/book/week15/image-1.png
  src/os2024/book/week15/image-2.png
  src/os2024/book/week15/image-3.png
  src/os2024/book/week15/image-4.png
  src/os2024/book/week15/image-5.png
  src/os2024/book/week15/image.png
Labels: documentation, Review effort [1-5]: 2

#189 Update data-integrity.md
  src/os2024/book/week14/data-integrity.md
Labels: documentation, Review effort [1-5]: 1

#188 feat: Update project progress by heeson16
  src/os2024/book/projects/202021029/homework-w2
  src/os2024/book/projects/202021029/homework-w3
  src/os2024/book/projects/202021029/index.md
Labels: documentation, Review effort [1-5]: 2

#205 Fix typo
  src/os2024/book/week02/cpu-intro.md
Labels: documentation, Review effort [1-5]: 1, Bug fix

#203 혜진 파일 전부 제출
  src/os2024/book/projects/ohgpwls/final.c
  src/os2024/book/projects/ohgpwls/index.md
Labels: documentation, Review effort [1-5]: 2

#201 project and homework
  src/os2024/book/projects/202321010/hw_wk02.md
  src/os2024/book/projects/202321010/hw_wk03.md
  src/os2024/book/projects/202321010/hw_wk04.md
  src/os2024/book/projects/202321010/hw_wk06.md
  src/os2024/book/projects/202321010/hw_wk07.md
  src/os2024/book/projects/202321010/index.md
  src/os2024/book/projects/202321010/reverse/reverse.c
Labels: documentation, enhancement, Review effort [1-5]: 3

#200 feat: initialize project directory of 202321017
  src/os2024/book/projects/202321017/grep.c
Labels: enhancement, Review effort [1-5]: 2

#199 Park eun seong kr/project patch 1
  src/os2024/book/projects/202121006/code
  src/os2024/book/projects/202121006/index.md
  src/os2024/book/projects/202121006/input.txt
Labels: documentation, enhancement, Review effort [1-5]: 3
